service: sls-marvel
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  sls-marvel:
    handler: index.handler
    events:
      - httpApi:
          path: /sls-marvel
          method: get
